name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Триггер для всех коммитов в ветку main
    tags:
      - 'v*' # Триггер для тегов, начинающихся с "v"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-app:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-app:latest

  deploy-to-kubernetes:
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/v') # Выполняется только для тегов
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Yandex Cloud CLI
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh  | bash

      - name: Add yc to PATH explicitly
        run: |
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Verify yc installation
        run: yc --version

      - name: Authorize Yandex Cloud CLI
        run: |
          yc config set token ${{ secrets.YC_TOKEN }}
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Get Kubernetes Cluster Credentials
        run: |
          yc managed-kubernetes cluster get-credentials ${{ secrets.K8S_CLUSTER_ID }} --external --force

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/nginx-test-app nginx-test-app=juliejool/nginx-app:latest -n test-app
